#文件临时存储路径
profilePath=D:/jxmx/uploadPath
#发件人地址
fromAddress=1813210023@qq.com


#项目启动端口
serverPort=8089


#数据库配置
druid.master.url=jdbc:mysql://4.216.34.103:3307/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
druid.master.username=root
druid.master.password=1982570424



#redis参数
redis.host=127.0.0.1
redis.port=6379
redis.password=123456
redis.database=15
redis.timeout=10s

#邮箱配置
mail.host=smtp.qq.com
mail.username=1813210023@qq.com
mail.password=hinlalqdwmyvdajg

#微信小程序配置
miniapp.appid=a
miniapp.secret=a
miniapp.token=a
miniapp.aesKey=a


