upload:
  path: @profilePath@

#elastic配置
easy-es:
  enable: true #默认为true,若为false则认为不启用本框架
  address: 127.0.0.1:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  username: elastic #若无 则可省略此行配置
  password: 1982570424 #若无 则可省略此行配置
  keep-alive-millis: 30000 # 心跳策略时间 单位:ms
  connect-timeout: 5000 # 连接超时时间 单位:ms
  socket-timeout: 600000 # 通信超时时间 单位:ms
  request-timeout: 5000 # 请求超时时间 单位:ms
  connection-request-timeout: 5000 # 连接请求超时时间 单位:ms
  max-conn-total: 100 # 最大连接数 单位:个
  max-conn-per-route: 100 # 最大连接路由数 单位:个
  global-config:
    db-config:
      id-type: customize


  # 全局线程池相关配置
thread-pool:
  # 是否开启线程池
  enabled: true
  # 核心线程池大小
  corePoolSize: 8
  # 最大可创建的线程数
  maxPoolSize: 16
  # 队列最大长度
  queueCapacity: 128
  # 线程池维护线程所允许的空闲时间
  keepAliveSeconds: 300
  # 线程池对拒绝任务(无线程可用)的处理策略
  # CallerRunsPolicy 等待
  # DiscardOldestPolicy 放弃最旧的
  # DiscardPolicy 丢弃
  # AbortPolicy 中止
  rejectedExecutionHandler: ''

--- # redisson 客户端配置
redisson:
  # 线程池数量
  threads: 16
  # Netty线程池数量
  nettyThreads: 32
  # 传输模式
  transportMode: "NIO"
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${base-work.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 32
    # 连接池大小
    connectionPoolSize: 64
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 如果尝试在此限制之内发送成功，则开始启用 timeout 计时。
    retryAttempts: 3
    # 命令重试发送时间间隔，单位：毫秒
    retryInterval: 1500
    # 发布和订阅连接的最小空闲连接数
    subscriptionConnectionMinimumIdleSize: 1
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50
    # 单个连接最大订阅数量
    subscriptionsPerConnection: 5
    # DNS监测时间间隔，单位：毫秒
    dnsMonitoringInterval: 5000

# 微信开发配置
wx:
  # 微信小程序开发
  miniapp:
    appid: @miniapp.appid@
    secret: @miniapp.secret@
    # 配置消息推送需要
    token: @miniapp.token@
    aesKey: @miniapp.aesKey@
    msgDataFormat: JSON
    # 存储类型
    config-storage:
      type: redistemplate
  #公众号配置
wechat:
  appId: @wechat.appId@
  appSecret: @wechat.appSecret@
  tempId: @wechat.tempId@
  myBirthday: @wechat.myBirthday@
  babyBirthday: @wechat.babyBirthday@
  loveDay: @wechat.loveDay@
#彩虹屁接口
tianapi:
  appKey: @tianapi.appKey@
  area: @tianapi.area@
## mybatis-plus相关配置
#mybatis-plus:
#  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  # 指定实体类的包,多个package用逗号或者分号分隔
#
#  # 以下配置均有默认值,可以不设置
#  global-config:
#    db-config:
#      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: AUTO
#      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
#      field-strategy: NOT_EMPTY
#      #数据库类型
#      db-type: MYSQL
#  configuration:
#    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    map-underscore-to-camel-case: true
#    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#    call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  # 自定义TypeHandler
  type-handlers-package: com.base.test.common.config.typehandle
  mapperPackage: com.base.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.base.**.domain
  global-config:
    #是否控制台
    banner: false
    db-config:
      #主键类型
      id-type: auto

captcha:
  # 验证码开关
  enabled: true
  # 验证码类型 math 数组计算 char 字符验证
  type: math
  # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
  category: line
  # 数字验证码位数
  numberLength: 1
  # 字符验证码长度
  charLength: 4

server:
  port: @serverPort@

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

feign:
  url: @feign.url@

elasticsearch:
  address: @es.address@
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100
  schema: http

  username: @es.username@
  password: @es.password@

#xxl-job
xxl:
  job:
    admin:
      #调度器ip地址
      #addresses: http://192.168.70.128:9090/xxl-job-admin
      addresses: http://127.0.0.1:9090/xxl-job-admin
      #addresses: http://4.216.34.103:9090/xxl-job-admin


    executor:
      #执行器ip地址
      #address: http://192.168.0.12:9999
      address: http://127.0.0.1:9999
      appname: xxl-job-executor-sample
      ip: 192.168.0.12
      port: 9999
      logpath: /data/applogs/xxl-job/xxx
      logretentiondays: -1
    accessToken: default_token






spring:
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profileActive@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      #设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      datasource:
        # 主库数据源
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: @druid.master.url@
          username: @druid.master.username@
          password: @druid.master.password@
        # 从库数据源
        slave:
          driverClassName: com.mysql.cj.jdbc.Driver
          url:
          username:
          password:
  druid:
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 注意这个值和druid原生不一致，默认启动了stat
    filters: stat
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      # 设置白名单，不填则允许所有访问
      allow:
      url-pattern: /druid/*
      # 控制台管理用户名和密码
      login-username: druid
      login-password: 123456
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

    # 设置连接有效时间

    undertow:
      #    http post请求数量的最大值，0表示不限制
      max-http-post-size: 0

      accesslog:
        dir: F://
        enabled: true
        pattern: common
        prefix: access_log
        suffix: .log
  #  jackson

  redis:
    # 地址
    host: @redis.host@
    # 端口，默认为6379
    port: @redis.port@
    # 数据库索引
    database: @redis.database@
    # 密码
    password: @redis.password@
    # 连接超时时间
    timeout: @redis.timeout@
    # 是否开启ssl
    ssl: false


  mail:
    host: @mail.host@
    username: @mail.username@ # 发件人邮箱
    password: @mail.password@ # 邮箱授权码
    default-encoding: UTF-8
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: @rabbitmq.host@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
    #	4369 -- erlang发现口    5672 --client端通信口    15672 -- 管理界面ui端口    25672 -- server间内部通信口
    #	如果采用java等等，连接rabbitmq 应该使用：5672
    port: @rabbitmq.port@
    publisher-confirm-type: @rabbitmq.publisher-confirm-type@
    publisher-returns: true
    template:
      mandatory: true
