spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.71.199:3307/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 1982570424
    hikari:
      max-lifetime: 30000
    # 设置连接有效时间

  redis:
    #  地址
    host: 127.0.0.1
    #  连接端口
    port: 6379
    #  连接密码（默认为空）
    password: 123456
    pool:
      #  连接池最大连接数（使用负值表示没有限制）
      max-active: 2000
      #  连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #  连接池中的最大空闲连接
      max-idle: 500
      #  连接池中的最小空闲连接
      min-idle: 0
    #  连接超时时间（毫秒）
    timeout: 3000
    #  Redisson配置 spring.redisson.singleServerConfig
    redisson:
      # 线程池数量
      threads: 16
      # Netty线程池数量
      nettyThreads: 32
      # 传输模式
      transportMode: "NIO"
      # 单节点配置
      singleServerConfig:
        # 客户端名称
        clientName: ${ruoyi.name}
        # 最小空闲连接数
        connectionMinimumIdleSize: 32
        # 连接池大小
        connectionPoolSize: 64
        # 连接空闲超时，单位：毫秒
        idleConnectionTimeout: 10000
        # 命令等待超时，单位：毫秒
        timeout: 3000
        # 如果尝试在此限制之内发送成功，则开始启用 timeout 计时。
        retryAttempts: 3
        # 命令重试发送时间间隔，单位：毫秒
        retryInterval: 1500
        # 发布和订阅连接的最小空闲连接数
        subscriptionConnectionMinimumIdleSize: 1
        # 发布和订阅连接池大小
        subscriptionConnectionPoolSize: 50
        # 单个连接最大订阅数量
        subscriptionsPerConnection: 5
        # DNS监测时间间隔，单位：毫秒
        dnsMonitoringInterval: 5000
